# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    feedmeuser_manager.class: Feedme\FeedmeUserBundle\Model\Service\FeedmeUserManager

services:
    kernel.listener.kernel_request:
           class: Feedme\AppBundle\EventListener\ErrorRedirect
           arguments:
               router: "@router"
           tags:
               - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    feedmeuserbundle.registration.form.type:
        class:  Feedme\FeedmeUserBundle\Form\Type\RegistrationFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: feedme_user_registration  }
    feedmeuserbundle.profile.form.type:
        class:  Feedme\FeedmeUserBundle\Form\Type\ProfileFormType
        arguments:  [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: feedme_user_profile  }
    feedme.user.manager:
        class:  %feedmeuser_manager.class%
        arguments:  ["@fos_user.user_manager", "@translator", "@gravatar.api"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
